### ISSUE TITLE
plot two alignments

### ISSUE THREAD

**Issue by xbarvazx** [schneebergerlab/plotsr#12]
Hi,

Is it possible to plot two syri alignments together?

A vs B
C vs B

How should the genome.txt file look like?

Best,
Raz

**Comment by mnshgl0110** [comment]
Hi Raz,

This is not supported natively, but I think it can be done.

In the genomes.txt use A, B , C, B.

For A vs B and C vs B use syri annotation. For the B vs C comparison, create a dummy annotation file which have 1bp syntenic regions between the homologous chromosomes (chromosomes having syntenic regions between the C vs B comparison would be homologous). I would assume that the 1bp syntenic region between B vs C would not be visible in the final plot given the impression that the only A vs B and C vs B are plotted.

Unfortunately, this is the best I can think of right now.

Alternatively, you may consider A vs B and B vs C comparison, which would be straightforward.

Best
Manish

**Comment by xbarvazx** [comment]
Hi Manish,

Thanks for the answer!
I will try, but now that I know I will just plan the alignments to fit the plotting, no problem.

Best,
Raz
