### ISSUE TITLE
Can I remove the dotted line of the coordinate axis

### ISSUE THREAD

**Issue by zhoudreames** [schneebergerlab/plotsr#13]
<img width="185" alt="image" src="https://user-images.githubusercontent.com/54714639/158163793-65d0c7c2-f737-47be-9758-097c4fc3ac74.png">
 In the background of the picture， there are some grey dotted lines of the coordinate axis. can I remove it ? thanks~

**Comment by mnshgl0110** [comment]
There is yet no parameter to disable that.

But, you can "hack" the code to get this simply by commenting out https://github.com/schneebergerlab/plotsr/blob/fffa3b722eae0df0f5445855e4c0563451690cd2/plotsr/func.py#L1228 and https://github.com/schneebergerlab/plotsr/blob/fffa3b722eae0df0f5445855e4c0563451690cd2/plotsr/func.py#L1271 before installing plotsr. So, you would need to git clone, edit func.py, and then install. However, this would remove the background grid permanently. And you would need to reinstall to get them back.

**Comment by zhoudreames** [comment]
> There is yet no parameter to disable that.
> 
> But, you can "hack" the code to get this simply by commenting out
> 
> https://github.com/schneebergerlab/plotsr/blob/fffa3b722eae0df0f5445855e4c0563451690cd2/plotsr/func.py#L1228
> 
> and
> https://github.com/schneebergerlab/plotsr/blob/fffa3b722eae0df0f5445855e4c0563451690cd2/plotsr/func.py#L1271
> 
> before installing plotsr. So, you would need to git clone, edit func.py, and then install. However, this would remove the background grid permanently. And you would need to reinstall to get them back.
following in your methods ，I git clone the software,edit func.py, and then install. but there are remains grey dotted lines of the coordinate axis in picture. why ? thanks for your help.

**Comment by zhoudreames** [comment]
<img width="364" alt="image" src="https://user-images.githubusercontent.com/54714639/158180811-21d166ea-b30f-4201-942d-b2ef700e2ebc.png">
