### ISSUE TITLE
plotting chromosomes with global synteny and large rearrangements

### ISSUE THREAD

**Issue by lassancejm** [schneebergerlab/plotsr#16]
Hi, 

I would like to visualize the synteny and rearrangements between a few (mammalian) genomes. 
While the 'classic' circos-type layout works, I think plotsr's layout has benefits and I wanted to give it a whirl. 
![image](https://user-images.githubusercontent.com/14118139/164477255-d279f609-3956-4713-a875-f5601fd956d2.png)
I produced the alignments using mummer. However, syri complains and gives me the following error:
```
Reading Coords - WARNING - Chromosomes IDs do not match.
Reading Coords - ERROR - Unequal number of chromosomes in the genomes. Exiting 
```
The assemblies are at the chromosome level, but differ indeed in chromosome number due to fusion/fission. Is there a way to circumvent this problem?

Thanks!

**Comment by mnshgl0110** [comment]
Check this https://github.com/schneebergerlab/syri/issues/136
