### ISSUE TITLE
Font error when running example

### ISSUE THREAD

**Issue by pspealman** [schneebergerlab/plotsr#18]
Hello,

I'd recently installed plotsr (using the conda install -c bioconda method) and when trying to run the example case I encounter an error:

File "/scratch/ps163/miniconda3/envs/plotsr/lib/python3.9/site-packages/plotsr/func.py", line 298, in addtags
    raise ValueError("Selected font {} at marker position {}:{}-{} is not available. Check plotsr_available_font_names.txt for list of available system markers".format(v, self.chr, self.start, self.end))
ValueError: Selected font Arial at marker position Chr3:4035330-4035331 is not available. Check plotsr_available_font_names.txt for list of available system markers

I've verified this using RHEL 8.4 and Ubuntu 20.04

**Comment by mnshgl0110** [comment]
Hi Pieter,

The example case uses the Arial font (check the `tf` tag in [markers.bed](https://github.com/schneebergerlab/plotsr/blob/master/example/markers.bed)). But it seems that plotsr cannot find this font type on the machines that you are using. Plotsr would have created `plotsr_available_font_names.txt` file containing the list of available fonts. Changing Arial in markers.bed to one of the available fonts would resolve this issue.

Best
Manish

**Comment by pspealman** [comment]
Manish,

Thank you for your rapid reply. 
After also changing the font in the tracks.txt file the example ran perfectly.

**Comment by zjwang6** [comment]
Hi，
I got the same errror，and I can not find the file of plotsr_available_font_names.txt. Could you give me some suggestion.
Thank you

**Comment by zjwang6** [comment]
> It should be in your working directory

Thank you. I find it.
