### ISSUE TITLE
Plotting gene annotation track without counting in bins

### ISSUE THREAD

**Issue by markcharder** [schneebergerlab/plotsr#2]
Dear Manish,

It is not clear in the online documentation how you produced the example plot containing a gene track (blue genes) without counting the genes in bins as for the SNPs.

Please can you add to the documentation explaining how this can be done or remove this from the example if it cannot be done.

Many thanks.

**Comment by mnshgl0110** [comment]
Hi Mark,
Thanks for pointing this out. I have updated the README to include this.

Basically, GFFs can be added as tracks like this:

`TAIR10_GFF3_genes.gff   Genes   ft:gff;bw:10000;nc:black;ns:8;nf:Arial;lc:blue;lw:4;bc:lightblue;ba:0.5`

The `ft` tag specifies that this is a GFF file. Plotsr can then plot the transcribed region (annotated as 'mRNA' in GFF) and the coding sequence (annotated as 'CDS').

Please let me know if there are still issues.

Best.

**Comment by markcharder** [comment]
Hi Manish,

Thank you for the quick response. This works - I've made some nice plots.

Best,
Mark
