### ISSUE TITLE
Can we plot two annotation tracks?

### ISSUE THREAD

**Issue by code-acc** [schneebergerlab/plotsr#21]
Hi Manish!

This is an excellent tool! Thank you for creating it! Is there a way to show two annotation tracks? 

I would like to have an annotation for F3.hap2 in the figure below. 

![image](https://user-images.githubusercontent.com/57204282/173247991-f91fa3cf-9d3d-4c80-8895-b61ef6dfdf63.png)

Right now, it's working with CS10.hap1 annotation. but if I make a tracks.txt as below:

CS10.gff3_polished      Genes   ft:gff
BS3.gff3_polished      Genes   ft:gff

I get the following error:

ValueError: Incomplete line in track file.
BS3.gff3_polished      Genes   ft:gff
File path and name are necessary columns, tags is optional column

Is there any solution?

Thanks,
Minal

**Comment by mnshgl0110** [comment]
Hi Minal,

It is possible to have multiple annotation tracks:
![image](https://user-images.githubusercontent.com/16225647/173310426-747bc965-7b92-4ba8-a03a-fb6f96ae136b.png)

Please ensure that the columns of tracks.txt are separated by tabs (and not spaces). That should resolve this issue.

Best
Manish

**Comment by code-acc** [comment]
Ahh! I thought it was tab-delimited but it wasn't! I have this figure now (below). Have other questions - 1. Is it possible to shift the label "Genes" towards more right side? and 2. Is it possible to have one annotation at the top and another at the bottom? In this case, I would like to have an annotation of F3.hap2 below F3.hap2 (orange line).

![image](https://user-images.githubusercontent.com/57204282/173388899-b8cd5ce6-296f-411f-a0b7-094ec0d2e261.png)

Thank you,
Minal

**Comment by mnshgl0110** [comment]
Hi Minal,

>  1. Is it possible to shift the label "Genes" towards more right side?

I have [added](https://github.com/schneebergerlab/plotsr/blob/master/example/tracks.txt) 'nm' tag for the tracks.txt which should allow manually adjustment to the track name like below (check [here](https://github.com/schneebergerlab/plotsr/blob/master/example/tracks.txt))
![image](https://user-images.githubusercontent.com/16225647/173407175-eea93e96-1970-4bf8-8b50-e9b94c029d5f.png)

You can give this a try and hopefully it would run without bugs.

> 2. Is it possible to have one annotation at the top and another at the bottom?

No that is not possible. This feature would be unusable when more than 2 genomes are being compared and would require quite a lot of work to add, so I do not think this will be added.

Best
Manish

**Comment by mnshgl0110** [comment]
Have you updated plotsr?
