### ISSUE TITLE
Mark contigs

### ISSUE THREAD

**Issue by Li-280512** [schneebergerlab/plotsr#25]
Your software is very well designed, but I have encountered some problems in using it. When I tagged contigs on the genome, I found that the color of large segments of contigs could not effectively cover the corresponding interval of the chromosome, so the size of MS needs to be adjusted, but I could not set the size accurately. Is there a way to mark this long fragment without having to resize the tag?

**Comment by Li-280512** [comment]
Hi
      Thank you very much for your reply!!
I want to mark the assembled chromosomes, which consist of several contigs,I want to graph it as follows


But when I used the --markers parameter and gave the CHR, START, END of the contig on the chromosome, the picture was as follows
Contig doesn't actually cover the chromosomes as I gave you.I guess it's because the "ms" in the Mark file I gave is too small, but I don't know how big this parameter should be.






| |
李嘉鑫
|
|
***@***.***
|
---- Replied Message ----
| From | Manish ***@***.***> |
| Date | 7/20/2022 16:34 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [schneebergerlab/plotsr] Mark contigs (Issue #25) |

I am not sure I get the issue completely. Could you please share some example? - Manish

**Comment by mnshgl0110** [comment]
Your reply does not have the figures, please reupload. Also, please share the markers.bed file as well.

**Comment by mnshgl0110** [comment]
Hi. Should be fixed with the updated version (https://github.com/schneebergerlab/plotsr/commit/bf26d9279919e7863cd016b128677942b0038d1b). Please update plotsr using the following commands and retry.
```
git clone https://github.com/schneebergerlab/plotsr.git
cd plotsr
python setup.py install
```

**Comment by Li-280512** [comment]
Thank you very much for your help!
I downloaded the latest plotsr==0.5.5, but when I run "plostr -h" it reported the following error, can you help me to see what the problem is.
![image](https://user-images.githubusercontent.com/109656459/180229206-03ae5be4-e9d1-44c2-84b7-999e4f9b07fa.png)

![image](https://user-images.githubusercontent.com/109656459/180229139-e9ebb2e0-d17f-4f1f-ba4f-960b27bb0b18.png)

![image](https://user-images.githubusercontent.com/109656459/180229071-60d1f486-8748-4412-8cc4-eea670dbbada.png)

**Comment by mnshgl0110** [comment]
Hi @Li-280512, sorry for the issues. Could you please re-install again? Let me know if it is still not working.

**Comment by Li-280512** [comment]
Hi @mnshgl0110 
  Thank you for your help!!! An updated version is available. It's a really great job, thanks again.
   I may trouble you again if there are more questions later...
