### ISSUE TITLE
Number of re-arrangement

### ISSUE THREAD

**Issue by Karimi-81** [schneebergerlab/plotsr#27]
Hi there,
I wonder if it is possible to count the number of all rearrangements through the output of plotsr. I require to find the number of different structural re-arrangement between two close species having large chromosome-level assemblies.  I appreciate if you could help me.

**Comment by mnshgl0110** [comment]
Plotsr only visualises the structural rearrangements identified by other tools. In case, you used syri for SR identification, then it would have created a summary file with the number and length of rearrangements.
