### ISSUE TITLE
Plot genes in tracks without structural annotation?

### ISSUE THREAD

**Issue by kushalsuryamohan** [schneebergerlab/plotsr#3]
Hi,
I am working with 10 scaffolded assemblies based on a combination of long-read, optical mapping and Hi-C data.
How memory-intensive will it be to generate the structural variant data for this set of genomes?
Also, I want to visualize specific families of genes and their orthologs across the 10 genomes. Can I visualize the genes between the genomes without needing to generate the structural variation data?
Appreciate your help.

**Comment by mnshgl0110** [comment]
Hi Kushal,

Are your scaffolded assemblies at chromosome-level? Or can you create pseudo-chromosomes from the scaffolds? Plotsr is designed keeping chromosome-level assemblies in mind. If the assemblies are not at chromosome-level then it would not be possible to group homologous chromosomes between genomes. This is a prerequisite when comparing multiple genomes with plotsr.

Once the assemblies are at chromosome-level, you can easily and align and call structural rearrangements between them. This is generally not too resource intensive.

In case chromosome-level assemblies are not possible, then you can try to trick plotsr by manually defining homologous scaffolds across genomes as syntenic and providing that as annotation (BEDPE files). But, I think, that might become too cumbersome then to just create pseudo-chromosome level assemblies.

Hope this helps.
Manish
