### ISSUE TITLE
the parameter --reg  can not show Translocation

### ISSUE THREAD

**Issue by aaannaw** [schneebergerlab/plotsr#31]
Hello
I wang to plot only a specific region. So my command is:  `software/plotsr/bin/plotsr --sr 03.syri.out --genomes 04.genomes.txt --reg B:Chr1:150000000-191956155 -o 1.Chr1fission.output_plot.pdf.` But I can not get the Transloction  around 160M on the Chr1. However the Transloction can be plotted when I use `--chr  Chr1` with the command：`software/plotsr/bin/plotsr --sr 03.syri.out --genomes 04.genomes.txt --chr Chr1  -o 1.Chr1fission.output_plot.pdf`.
Could you give me any suggestions?
Thanks very much!
![image](https://user-images.githubusercontent.com/109299053/198878534-13c70b57-d2a3-4219-a260-213fd5875a1d.png)
![image](https://user-images.githubusercontent.com/109299053/198878591-b64041ae-34cd-48df-89da-4f1da0165cfa.png)

**Comment by mnshgl0110** [comment]
Using `--rtr` should solve this. Check https://github.com/schneebergerlab/plotsr/issues/7

**Comment by aaannaw** [comment]
It works! Thanks!
