### ISSUE TITLE
Getting exact coordinates in an inversion/insertion region in a chromosome

### ISSUE THREAD

**Issue by LandiMi2** [schneebergerlab/plotsr#36]
Hey folks! This is such a lovely tool for comparative genomics!! I am trying to get coordinates of where I have an insertion in one chromosome (reference) and not in the query. How can I extract the exact coordinates where I visualize this insertion towards the end? I am interested in the inversion coordinates too.
Here is the plot 
![Screenshot 2022-12-23 at 13 29 57](https://user-images.githubusercontent.com/47971974/209336825-4e5e7cfa-02b2-4da7-b20d-1c44f2317b54.png)

**Comment by mnshgl0110** [comment]
Hi Michael, you can get the coordinates from the syri's output file (syri.out and syri.vcf). Also, ```insertion in one chromosome (reference) and not in the query``` is defined as a deletion (DEL) in syri's output.

**Comment by LandiMi2** [comment]
@mnshgl0110 thanks! I will closely look at it. Do you have any documentation to syri's outputs?

**Comment by LandiMi2** [comment]
@mnshgl0110 I also don't understand this error message when running plotsr
![Screenshot 2022-12-23 at 15 44 59](https://user-images.githubusercontent.com/47971974/209354087-e1c478b5-8bbe-4b8a-814d-9940adc90222.png)

**Comment by mnshgl0110** [comment]
syri documentation: https://schneebergerlab.github.io/syri/

regarding the error: I guess there would be some issue in the genomes.txt file. Make sure that it has correct file format. Specifically, ensure that the columns are separated by tabs and not spaces.

**Comment by LandiMi2** [comment]
Aha, tabs, not gaps, yes, yes. Mine needed to be fixed with how I named the file (with no dots but maybe underscore uppercase and lowercase). For some reason, naming your file with the dots tab doesn't work. It works after a space, then a tab. Stupid me dint know this 😀
