### ISSUE TITLE
How to get high-definition pictures

### ISSUE THREAD

**Issue by zhoudreames** [schneebergerlab/plotsr#37]
This is my code：
```
plotsr --sr syri.out --genomes genomes.txt -o 1.pdf -S 0.35 --chrord chrom -s 10000 -b pdf -H 12 -W 7 --cfg base.ctg &
```
I got 134k 1.pdf files:
[1.pdf](https://github.com/schneebergerlab/plotsr/files/10526879/1.pdf)
but this picture doesn't look high definition， how to get the high-definition pictures？ thanks~

**Comment by mnshgl0110** [comment]
Did you mean to say that plotsr generated 134,000 output plot files all names 1.pdf? I do not think that is possible.

Have you tried the example commands in plotsr.sh  (https://github.com/schneebergerlab/plotsr/tree/master/example)? How did the output look?
