### ISSUE TITLE
use for protein sequences

### ISSUE THREAD

**Issue by LandiMi2** [schneebergerlab/plotsr#38]
Is it possible to use this tool for protein sequences? Trying to compare two haplotypes predicted proteins. Plotting synteny blocks for these predicted protein sequences

**Comment by mnshgl0110** [comment]
This has not been tested, but I would guess that as long as you can find synteny between the protein haplotypes, plotsr would work. I cannot recall anything specific that would inhibit this but I am not sure how easy this would be.
This is an interesting question and an optional feature update. In case you try it out then I would appreciate if you could your experience.

**Comment by LandiMi2** [comment]
I will give it a try and share my experience.
