### ISSUE TITLE
Error importing pysam.

### ISSUE THREAD

**Issue by bijendrabio** [schneebergerlab/plotsr#39]
Hello, 
I received following error while running syRI:
$ syri -c A_B.bam -r A.fa -q B.fa -F B --pref

Traceback (most recent call last):
  File "syri/pyxFiles/synsearchFunctions.pyx", line 240, in syri.synsearchFunctions.readCoords
  File "syri/pyxFiles/synsearchFunctions.pyx", line 117, in syri.synsearchFunctions.readSAMBAM
  File "/home/miniconda3/envs/plotsr/lib/python3.8/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Kindly suggest!

Kind regards,
B

**Comment by mnshgl0110** [comment]
Hi. It seems that you have missing libraries in your environment and as a result pysam cannot load properly. You can try this:
https://unix.stackexchange.com/questions/283607/libraries-libcrypto-so-1-0-0-cannot-open-shared-object-file-no-such-file-or-d
Or reinstall pysam in a new work python environment. Or can also contact pysam developers https://github.com/pysam-developers/pysam

**Comment by bijendrabio** [comment]
@mnshgl0110 Got it. I solved it. Thanks

**Comment by bijendrabio** [comment]
> Hi. It seems that you have missing libraries in your environment and as a result pysam cannot load properly. You can try this: https://unix.stackexchange.com/questions/283607/libraries-libcrypto-so-1-0-0-cannot-open-shared-object-file-no-such-file-or-d Or reinstall pysam in a new work python environment. Or can also contact pysam developers https://github.com/pysam-developers/pysam
