### ISSUE TITLE
readsyriout - WARNING

### ISSUE THREAD

**Issue by Yutang-ETH** [schneebergerlab/plotsr#4]
Hi Manish

I always got these warming messages:

readsyriout - WARNING - DUPAL is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - SYNAL is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - SNP is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - INS is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - DEL is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - HDR is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - NOTAL is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - INVDPAL is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - INVTRAL is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - TRANSAL is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - CPG is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - CPL is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - INVAL is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.
readsyriout - WARNING - TDM is not a valid annotation for alignments in file chr1_syri.out. Alignments should belong to the following classes ['SYN', 'INV', 'TRANS', 'INVTR', 'DUP', 'INVDP']. Skipping alignment.

my input for plotsr is the output of SyRI and my whole genome alignment was done by Nucmer4 following your tutorial.

Are the warming messages normal? Should I ignore them? I got my plots though.

Best wishes,
Yutang

**Comment by mnshgl0110** [comment]
Hi Yutang, Yes you can ignore these warning message. In fact, in the current version plotsr would not throw these warnings when reading syri output.
