### ISSUE TITLE
Customizing the color code used for representing different input genomes

### ISSUE THREAD

**Issue by yjx1217** [schneebergerlab/plotsr#41]
Hello,

I was wondering if there is a way to customize color code used for representing different input genomes.
By default, plotsr seems to automatically assign the color to each genome. It will be great if this can be customized.

Thanks!

Best,
Jia-Xing

**Comment by mnshgl0110** [comment]
Yes, already described in the README https://github.com/schneebergerlab/plotsr#genomes

**Comment by yjx1217** [comment]
I see! Many thanks!
