### ISSUE TITLE
the 'genome_id' in markers.bed

### ISSUE THREAD

**Issue by iehfdshgkjzh** [schneebergerlab/plotsr#43]
Dear Developer:

  I have some problems when writing markers.bed. I'm confused about the genome_id. My genome is a sample of Mannheimia haemolytica. Now I don't know if it's because I used the wrong genome_id or because plotsr doesn't support bacteria.
  My errors:
```
readannobed - WARNING - Incorrect marker information. Chromosome: tig00001 is not present in genome pha. Skipping it
```

Best
wu

**Comment by TZM9882** [comment]
> Genome ID corresponds to the name genome name as given in the `--genomes` input file. For example, if genomes.txt looks like this:
> 
> ```
> $genomes.txt
> #file	name	tags
> A.fa	A	lw:1.5
> B.fa	B	lw:1.5
> ```
> 
> Then the markers.bed would look like:
> 
> ```
> #chr	start	end genome_id	tags
> Chr3	4035330	4035331	A	mt:v;mc:black;ms:3;tt:Inversion 1;tp:0.02;ts:8;tf:Arial;tc:black
> Chr4	2322547	2322548	B	mt:^;mc:black;ms:3;tt:Inversion 2;tp:-0.07;ts:8;tf:Arial;tc:black
> Chr5	3322547	3322548	A	mt:^;mc:black;ms:3;tt:Inversion 2;tp:-0.07;ts:8;tf:Arial;tc:black
> ```

Dear Manish,

Apologies for disturbing you again with this.
I have a problem with plotting using "marker.bed" (image 1).
Image 2 is how I prepared for "genomes.txt" file and it works.
Image 3 is how I prepared for "marker.bed" file, but it doesn't work. I also tried with other possible names (as far as I can imagine) but, still same error message comes.

Please see the attached images and advise me with any instructions.

Sincerely and thanks,

![Screenshot 2023-07-03 at 22 02 59](https://github.com/schneebergerlab/plotsr/assets/129658757/9fed035d-9a6b-4586-a42f-c32e0047af0c)
![Screenshot 2023-07-03 at 22 04 22](https://github.com/schneebergerlab/plotsr/assets/129658757/8fa31a93-9f47-40ea-95bd-288c6930dd79)
![Screenshot 2023-07-03 at 22 07 55](https://github.com/schneebergerlab/plotsr/assets/129658757/c52eb296-7fac-4dd5-96df-794359b2ad02)

**Comment by mnshgl0110** [comment]
Based on the error message, I suspect that the column are separated by space. The columns in markers.bed should be tab-separated.
