### ISSUE TITLE
feature suggestion: using different shades of color to show sequence identity differences across different homologous blocks 

### ISSUE THREAD

**Issue by yjx1217** [schneebergerlab/plotsr#44]
Dear Developers,

For now, plotsr use a single color (grey by default) to display the sequence homology between homologous chromosomes. It will be great if plotsr could add an option to enable users to use different shades of the same color or even different colors  to denote the sequence identity differences  across different homologous blocks. For example, Easyfig (http://mjsull.github.io/Easyfig/) has such feature enabled, which is quite useful for some use scenarios.

Best,
Jia-Xing

**Comment by mnshgl0110** [comment]
Thanks for the suggestion. We recently added the functionality to allow users to provide colors for individual alignments (https://github.com/schneebergerlab/plotsr#customisation-alignments). You could give this a try by installing plotsr through github. Please note that this is a new feature and might have some issues. Of course, feedback will be appreciated.

**Comment by yjx1217** [comment]
Hi @mnshgl0110 ,

Thanks for the info! This new feature indeed looks useful, although my suggested feature might go a step further, which is automatically decide the colors based on sequence identity of the corresponding homology blocks and a user-provided color palette.

Best,
Jia-Xing
