### ISSUE TITLE
Custom alignment colors do not show

### ISSUE THREAD

**Issue by lgozasht** [schneebergerlab/plotsr#48]
Thank you for producing this awesome tool! I'm trying to provide custom colors for some structural variants in alignment file (in an additional column as suggested). However, when I run plotsr, alignments are still plotted with default colors. Perhaps I need to edit the base.cfg file or am making some other mistake. I would appreciate any assistance or suggestions!

Best,
Landen

**Comment by mnshgl0110** [comment]
Hi Landen,

Plotsr automatically checks the input syri.out/bed files for the extra column corresponding to alignment customisation. If it finds that column then it prints an output message like
```readbedout - WARNING - col_lersyri.filtered.color_lw_z.out.bed have extra annotation column dedicated for alignment customisation. Using it.```

Are you getting such a message? If not, then the issue might be with the editing of the input files. Please ensure that you use `tab` to separate the columns. Also, the changes need to be made in the structural annotation input files (and not the raw alignment files).

If you are getting the above message. Then, could you please share sample input files for me to check.

Best
Manish

P.S.: Also, check that you are using the latest version which allows this feature.

**Comment by lgozasht** [comment]
Hi Manish,

I appreciate your timely response! It seems that I was indeed using an older version. I downloaded the latest and it works beautifully!

Thank you!

Best,
Landen
