### ISSUE TITLE
Straight Line instead curve line between genes

### ISSUE THREAD

**Issue by awesomedeer** [schneebergerlab/plotsr#51]
Dear Goel @mnshgl0110 
I want to ask whether plotsr has the parameter to change the line between genes from curve to straight.

Best regards
Song

**Comment by mnshgl0110** [comment]
The genes in the tracks are straight lines only, so I assume you mean the alignments between the genomes. Currently, it is not possible to have them as straight lines. I am not even sure whether that would result in better visualisation compared to bezier paths. Is there any specific reason you would want them to be straight?
