### ISSUE TITLE
Error in genomes.txt

### ISSUE THREAD

**Issue by mnshgl0110** [schneebergerlab/plotsr#55]
hello Manih,

I am very new to this whole process but still trying my best using manuals and similar issues by previous users. Thanks to those unknown users.

I also got below the error for plotsr. I followed the instructions.
Am I still wrong somewhere?
Image 2 is how I prepared genomes.txt for 2 genomes (A is reference).
Please help me with this problem

Thanks,
Mg 

![Screenshot 2023-06-23 at 10 32 26](https://github.com/schneebergerlab/syri/assets/129658757/fb57d2a7-2e22-4516-a624-0de04d059cb1)

![Screenshot 2023-06-23 at 10 35 04](https://github.com/schneebergerlab/syri/assets/129658757/0f1df135-2f64-4a9a-8497-6f2fd82ffa4a)

_Originally posted by @TZM9882 in https://github.com/schneebergerlab/syri/issues/125#issuecomment-1603518786_

**Comment by mnshgl0110** [comment]
Hi @TZM9882. The file contains `$genomes.txt`. That should not be there. In the documentation, the `$` sign is used to show the command prompt.

**Comment by TZM9882** [comment]
> Hi @TZM9882. The file contains `$genomes.txt`. That should not be there. In the documentation, the `$` sign is used to show the command prompt.

Hello Sir, 

thank you for your quick reply. Actually, I noticed this mistake just after uploading my files, then I tried already by deleting this line including the hash-tagged line. But the same error message came again. I recorded a video of how I performed, but couldn't upload due to an unacceptable-sized file.

Am I still wrong somewhere and advise me please anything I can overcome this process.

Thankyou again and sincerely,


![Screenshot 2023-06-24 at 9 05 02](https://github.com/schneebergerlab/plotsr/assets/129658757/8ee19a61-37b5-4317-a8e3-5743a8fca180)

**Comment by TZM9882** [comment]
Hello Manish,

I just got the results.
How I got was that I copied formatted contents from issue #43 (actually, previous one either, I copied from somewhere recommended) and tried changing nothing but removing one line stated with $.
It worked. 

What my curiosity is (if you don't mind), is there any difference between the file format (from the developer site) and self-created txt.file (but followed the instructions for contents format, like columns are tab-separated)? 

Anyhow,
Thank you so much for taking care of everything

![Screenshot 2023-06-24 at 10 21 37](https://github.com/schneebergerlab/plotsr/assets/129658757/5385ab8f-dac6-4812-843b-f958e65d90af)

**Comment by mnshgl0110** [comment]
Difficult to say what caused this, my guess is encoding differences between windows and linux.

**Comment by yangruixue-xue** [comment]
> Difficult to say what caused this, my guess is encoding differences between windows and linux.

So how do you make genomes.txt files on linux? I've been getting errors when I edit it myself, but when I copy the one in question 34 it's fine! Looking forward to your reply, thank you。 @mnshgl0110
