### ISSUE TITLE
Sizes between inversions do not correspond across the genome

### ISSUE THREAD

**Issue by JAEYOONSUNG** [schneebergerlab/plotsr#56]
Hello! I obtained figures comparing three genomes using minimap2, SyRI, and plotsr. However, there seem to be issues where the sizes between inversions do not correspond and the representation of synteny is not detailed enough and appears too clustered. Is there a specific part of the command that I should modify to address these problems?

<img width="902" alt="스크린샷 2023-06-27 21 25 56" src="https://github.com/schneebergerlab/plotsr/assets/42233037/246af53e-f3f2-4689-bedc-b7d3964e6bbe">

**Comment by StanaW** [comment]
Hello! I came across the same problem with the sizes between inversions not corresponding. I was trying to search through the tool on the usage of --invgaplen, but I cannot find it. What do you specify as an argument? And how can I filter out inversions with very different sizes? Thank you for your help!

**Comment by mnshgl0110** [comment]
> I was trying to search through the tool on the usage of --invgaplen, but I cannot find it. What do you specify as an argument? 

`--invgaplen` is a parameter for syri. So you would need to rerun syri with this parameter if you do want inversions with large indels.


> And how can I filter out inversions with very different sizes? 

Rerun syri with the `--invgaplen` parameter. Or you can filter the input files for plotsr (for example: syri.out file) to remove such inversions.

**Comment by StanaW** [comment]
Thank you so much for your response! Yes, I wanted to rerun syri. But my question is what do you specify as the argument for the parameter "--invgaplen"? Is it the size you do not want the inversions to exceed?

**Comment by mnshgl0110** [comment]
Output from `syri  -h`:
```
 --invgaplen INVGL     Maximum allowed gap-length between two alignments of a multi-alignment inversion. It affects the selection
                        of large inversions that can have different length in the reference and query genomes. (default:
                        1000000000)
```

**Comment by StanaW** [comment]
Thank you so much! I am sorry, I have not noticed it there.
