### ISSUE TITLE
colour to non-aligned region

### ISSUE THREAD

**Issue by mnshgl0110** [schneebergerlab/plotsr#60]
Hi Plotsr Team,

I am currently using your amazing tool. Can I give color to non-aligned regions that are labeled as "NOTAL" in the syn.out file?

As for my second question, my top chromosomes' size appears to be bigger only at the end of the chromosomes, but I am also interested in showing the chromosome size difference at both ends.

Thank you for your assistance.
@ABDULLAHGUJJAR

https://github.com/schneebergerlab/syri/issues/203#issue-1821717065

**Comment by mnshgl0110** [comment]
Yes, you can annotate NOTAL, however since NOTAL regions do not have alignments, you would need to either use markers or tracks to show them.

I am not sure I understand your second question. What I can tell is currently, the chromosomes are left-aligned and it is not possible to center-align. I hope this helps.

**Comment by ABDULLAHGUJJAR** [comment]
Hi Manish Goel,

My second question is about chromosome length. When I am comparing two chromosomes, the top chromosome's length is bigger. The top chromosome's start and end have unique telomere sequences. However, the Figure starts from zero and does not show the NOTALL portion. Can I also show the difference in chromosome lengths?

Thanks for your cooperation.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mnshgl0110** [comment]
I would imagine that the plot would have not-aligned regions at the left end. Could you please share the figure so that I can better understand the issue?

**Comment by ABDULLAHGUJJAR** [comment]
[output-mar2.pdf](https://github.com/schneebergerlab/plotsr/files/12210265/output-mar2.pdf)
Hi Dear Manis Goel,
i am sharing figure here.
Actually i want to show Top chromosomes length is bigger due to telomere start and at the end

**Comment by mnshgl0110** [comment]
Hi @ABDULLAHGUJJAR. I would guess that the 5' telomeric region would be few KB long. Since, the chromosomes are ~44MB long, it is difficult to see the corresponding not-aligned region. I would suggest that you first check the syri output to confirm that the telomeric region is indeed not-aligned. Then, you can zoom in the 5' end to showcase the telomeric gap using the `--reg` parameter (something like A:chr1:1:1000000 might work).
