### ISSUE TITLE
tracks error

### ISSUE THREAD

**Issue by Hemaprasanth24** [schneebergerlab/plotsr#62]
hii i was using plotsr tool for plotting syri result 
if i plot without tracks file it is plotting when tracks file with gff file along it gives error
/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/plotsr/scripts/plotsr.py:259: UserWarning: The label '_child1' of <matplotlib.collections.LineCollection object at 0x7f6f8c73b550> starts with '_'. It is thus excluded from the legend.
  l1 = plt.legend(handles=chrlabels, loc='lower left', bbox_to_anchor=bbox_to_anchor, ncol=ncol, mode=None, borderaxespad=0., frameon=False, title='Genomes')
/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/plotsr/scripts/plotsr.py:259: UserWarning: The label '_child3' of <matplotlib.collections.LineCollection object at 0x7f6f8c738130> starts with '_'. It is thus excluded from the legend.
  l1 = plt.legend(handles=chrlabels, loc='lower left', bbox_to_anchor=bbox_to_anchor, ncol=ncol, mode=None, borderaxespad=0., frameon=False, title='Genomes')
/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/plotsr/scripts/plotsr.py:259: UserWarning: The label '_child4' of <matplotlib.collections.LineCollection object at 0x7f6f8cf9b9d0> starts with '_'. It is thus excluded from the legend.
  l1 = plt.legend(handles=chrlabels, loc='lower left', bbox_to_anchor=bbox_to_anchor, ncol=ncol, mode=None, borderaxespad=0., frameon=False, title='Genomes')
/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/plotsr/scripts/plotsr.py:259: UserWarning: The label '_child5' of <matplotlib.collections.LineCollection object at 0x7f6f8c73baf0> starts with '_'. It is thus excluded from the legend.
  l1 = plt.legend(handles=chrlabels, loc='lower left', bbox_to_anchor=bbox_to_anchor, ncol=ncol, mode=None, borderaxespad=0., frameon=False, title='Genomes')
/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/plotsr/scripts/plotsr.py:259: UserWarning: The label '_child11' of <matplotlib.collections.LineCollection object at 0x7f6f8c755f70> starts with '_'. It is thus excluded from the legend.
  l1 = plt.legend(handles=chrlabels, loc='lower left', bbox_to_anchor=bbox_to_anchor, ncol=ncol, mode=None, borderaxespad=0., frameon=False, title='Genomes')
/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/plotsr/scripts/plotsr.py:259: UserWarning: The label '_child17' of <matplotlib.collections.LineCollection object at 0x7f6f8c774430> starts with '_'. It is thus excluded from the legend.
  l1 = plt.legend(handles=chrlabels, loc='lower left', bbox_to_anchor=bbox_to_anchor, ncol=ncol, mode=None, borderaxespad=0., frameon=False, title='Genomes')
track - WARNING - Reading GFF file radioduransPROKKA_07052023.gff. Overlapping transcripts would be plotted as such without any filtering.
Traceback (most recent call last):
  File "/home/hemaprasanth/anaconda/envs/py3.8/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/plotsr/scripts/plotsr.py", line 334, in main
    plotsr(args)
  File "/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/plotsr/scripts/plotsr.py", line 276, in plotsr
    tracks = readtrack(TRACKS, chrlengths)
  File "/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/plotsr/scripts/func.py", line 857, in readtrack
    t.readdata(chrlengths)
  File "/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/plotsr/scripts/func.py", line 827, in readdata
    self._readgff(chrlengths)
  File "/home/hemaprasanth/anaconda/envs/py3.8/lib/python3.8/site-packages/plotsr/scripts/func.py", line 816, in _readgff
    k = list(model.keys())[0]
AttributeError: 'NoneType' object has no attribute 'keys'

**Comment by mnshgl0110** [comment]
Hi @Hemaprasanth24 . Could you please share the gff file?

**Comment by Hemaprasanth24** [comment]
ok thank you for your reply i have another question about clearing the
warnings on legend
