### ISSUE TITLE
Can i plot the centromere region?

### ISSUE THREAD

**Issue by lly1214** [schneebergerlab/plotsr#64]
I can not find the plot result of [Giraut2011_centromeres.bed](https://github.com/schneebergerlab/plotsr/blob/master/example/Giraut2011_centromeres.bed). How can i use "track" to plot the region but not density of my variations ?

**Comment by mnshgl0110** [comment]
This is shown in Fig. 2b of the plotsr manuscript. Also, check the example folder.
Just parsing the centromering BED file marks the centromeric region.

 ![image](https://github.com/schneebergerlab/plotsr/assets/16225647/19546bbb-14f2-4ed8-9aa5-d2d9fad59e11)
