### ISSUE TITLE
cannot plot all the information from syri.out file

### ISSUE THREAD

**Issue by Hemaprasanth24** [schneebergerlab/plotsr#65]
hi i using syri to find synteny, inversion, translocation, duplication in a bacterial genome  after getting syri.out file i have plotted it in plotsr but i can find only any one of these 4 type if synteny is present i cannot file inversion i have also checked the syri.out file it contions of both inversion as well as translocation

**Comment by mnshgl0110** [comment]
Probably the rearrangements in the bacterial genomes are quite small and therefore filtered out by plotsr. You can adjust the `-s` parameter of plotsr to visualise smaller rearrangements.

**Comment by Hemaprasanth24** [comment]
NZ_CP013910.1	1	75429	-	-	-	-	-	NOTAL1	-	NOTAL	-
NZ_CP013910.1	75430	405903	-	-	NZ_AP026560.1	83715	222402	SYN1	-	SYN	-
NZ_CP013910.1	75430	75869	-	-	NZ_AP026560.1	83715	84154	SYNAL1	SYN1	SYNAL	-
NZ_CP013910.1	75463	75463	T	G	NZ_AP026560.1	83748	83748	SNP3	SYN1	SNP	-
NZ_CP013910.1	75544	75544	G	A	NZ_AP026560.1	83829	83829	SNP4	SYN1	SNP	-
NZ_CP013910.1	75549	75549	T	C	NZ_AP026560.1	83834	83834	SNP5	SYN1	SNP	-
NZ_CP013910.1	75565	75565	G	C	NZ_AP026560.1	83850	83850	SNP6	SYN1	SNP	-
NZ_CP013910.1	75567	75567	G	C	NZ_AP026560.1	83852	83852	SNP7	SYN1	SNP	-
NZ_CP013910.1	75572	75572	C	G	NZ_AP026560.1	83857	83857	SNP8	SYN1	SNP	-
NZ_CP013910.1	75574	75574	C	G	NZ_AP026560.1	83859	83859	SNP9	SYN1	SNP	-
NZ_CP013910.1	75826	75826	A	G	NZ_AP026560.1	84111	84111	SNP10	SYN1	SNP	-
NZ_CP013910.1	75827	75827	C	A	NZ_AP026560.1	84112	84112	SNP11	SYN1	SNP	-
NZ_CP013910.1	75828	75828	A	G	NZ_AP026560.1	84113	84113	SNP12	SYN1	SNP	-
NZ_CP013910.1	75837	75837	A	C	NZ_AP026560.1	84122	84122	SNP13	SYN1	SNP	-
NZ_CP013910.1	75869	405463	-	-	NZ_AP026560.1	84154	221962	HDR1	SYN1	HDR	-
NZ_CP013910.1	405464	405903	-	-	NZ_AP026560.1	221963	222402	SYNAL2	SYN1	SYNAL	-
NZ_CP013910.1	405497	405497	T	G	NZ_AP026560.1	221996	221996	SNP14	SYN1	SNP	-
NZ_CP013910.1	405578	405578	G	A	NZ_AP026560.1	222077	222077	SNP15	SYN1	SNP	-
NZ_CP013910.1	405583	405583	T	C	NZ_AP026560.1	222082	222082	SNP16	SYN1	SNP	-
NZ_CP013910.1	405599	405599	G	C	NZ_AP026560.1	222098	222098	SNP17	SYN1	SNP	-
NZ_CP013910.1	405601	405601	G	C	NZ_AP026560.1	222100	222100	SNP18	SYN1	SNP	-
NZ_CP013910.1	405606	405606	C	G	NZ_AP026560.1	222105	222105	SNP19	SYN1	SNP	-
NZ_CP013910.1	405608	405608	C	G	NZ_AP026560.1	222107	222107	SNP20	SYN1	SNP	-
NZ_CP013910.1	405860	405860	A	G	NZ_AP026560.1	222359	222359	SNP21	SYN1	SNP	-
NZ_CP013910.1	405861	405861	C	A	NZ_AP026560.1	222360	222360	SNP22	SYN1	SNP	-
NZ_CP013910.1	405862	405862	A	G	NZ_AP026560.1	222361	222361	SNP23	SYN1	SNP	-
NZ_CP013910.1	405871	405871	A	C	NZ_AP026560.1	222370	222370	SNP24	SYN1	SNP	-
NZ_CP013910.1	405904	3084300	-	-	-	-	-	NOTAL2	-	NOTAL	-
NZ_CP013910.1	3084301	3084740	-	-	NZ_AP026560.1	824888	825327	INV2	-	INV	-
NZ_CP013910.1	3084301	3084740	-	-	NZ_AP026560.1	825327	824888	INVAL3	INV2	INVAL	-
NZ_CP013910.1	3084333	3084333	T	G	NZ_AP026560.1	825295	825295	SNP25	INV2	SNP	-
NZ_CP013910.1	3084342	3084342	T	C	NZ_AP026560.1	825286	825286	SNP26	INV2	SNP	-
NZ_CP013910.1	3084343	3084343	G	T	NZ_AP026560.1	825285	825285	SNP27	INV2	SNP	-
NZ_CP013910.1	3084344	3084344	T	C	NZ_AP026560.1	825284	825284	SNP28	INV2	SNP	-
NZ_CP013910.1	3084596	3084596	G	C	NZ_AP026560.1	825032	825032	SNP29	INV2	SNP	-
NZ_CP013910.1	3084598	3084598	G	C	NZ_AP026560.1	825030	825030	SNP30	INV2	SNP	-
NZ_CP013910.1	3084603	3084603	C	G	NZ_AP026560.1	825025	825025	SNP31	INV2	SNP	-
NZ_CP013910.1	3084605	3084605	C	G	NZ_AP026560.1	825023	825023	SNP32	INV2	SNP	-
NZ_CP013910.1	3084621	3084621	A	G	NZ_AP026560.1	825007	825007	SNP33	INV2	SNP	-
NZ_CP013910.1	3084626	3084626	C	T	NZ_AP026560.1	825002	825002	SNP34	INV2	SNP	-
NZ_CP013910.1	3084707	3084707	A	C	NZ_AP026560.1	824921	824921	SNP35	INV2	SNP	-
NZ_CP013910.1	3084741	3264334	-	-	-	-	-	NOTAL3	-	NOTAL	-
-	-	-	-	-	NZ_AP026560.1	1	83714	NOTAL4	-	NOTAL	-
-	-	-	-	-	NZ_AP026560.1	222403	824887	NOTAL5	-	NOTAL	-
-	-	-	-	-	NZ_AP026560.1	825328	3135460	NOTAL6	-	NOTAL	-



this is the result i got it from syri it contain inv also but it cannot be plotted by plotsr

**Comment by mnshgl0110** [comment]
did you use -s parameter?

**Comment by Hemaprasanth24** [comment]
thanks for the clarifiction and i also have another problem about labelling the problem
/home/hema/anaconda3/envs/py3.8/lib/python3.8/site-packages/plotsr/scripts/plotsr.py:259: UserWarning: The label '_child1' of <matplotlib.collections.LineCollection object at 0x7f9e56ec6df0> starts with '_'. It is thus excluded from the legend.
  l1 = plt.legend(handles=chrlabels, loc='lower left', bbox_to_anchor=bbox_to_anchor, ncol=ncol, mode=None, borderaxespad=0., frameon=False, title='Genomes')

**Comment by mnshgl0110** [comment]
As the original problem is resolved, I will close this issue. Please start a new issue for other problems. Also, do share the all relevant info like the command used, example input files, output generated.

**Comment by Hemaprasanth24** [comment]
thank you for the reply i just correct the errror
