### ISSUE TITLE
Plotting chromosome fusion

### ISSUE THREAD

**Issue by kashiff007** [schneebergerlab/plotsr#71]
Hi Manish,

I have been using this tool, and it's really nice. 

However, I want to compare two genomes, let's call them A and B. Genome A has one larger chromosome, which is the result of a fusion of two chromosomes from Genome B. Please refer to the attached image for clarification. 

I have attempted to do this, but the tool is giving an error, and I suspect it is due to one fewer chromosome in Genome A.

<img width="541" alt="image" src="https://github.com/schneebergerlab/plotsr/assets/16431099/ab30379a-7c63-4378-9dc2-1a8103cfd48e">

**Comment by mnshgl0110** [comment]
Hi @kashiff007. Currently, plotsr requires that the genomes have same number of chromosomes. So, unfortunately, it is not possible to generate this plot natively. You can consider manually fusing (concatenating) chromosome 8A and 10B in genome B, C, D and then draw this figure. It will be possible to highlight this fusion using `markers` (eg: fig3 from https://doi.org/10.1093/genetics/iyac132).

Also, I am glad that you like this tool. I guess you won't remember but we chatted briefly when I started my phd in MPIPZ. So, its great to hear from you again. Cheers.

**Comment by kashiff007** [comment]
Thanks @mnshgl0110 for your quick response and suggestion. I am trying this.

Off course I remember you  from MPIPZ. Good to see that you are developing great tools for us.
