### ISSUE TITLE
Labels to the left of each assembly

### ISSUE THREAD

**Issue by scottcain** [schneebergerlab/plotsr#74]
When I was showing some plotsr work to my boss (who is color blind), he pointed out that it is very difficult to discern which line corresponds to which assembly. It is, of course, especially hard for someone who is color blind but in reality, when I have 20+ assemblies I'm comparing, it is pretty difficult for me to tell different shades of color apart (I frequently end up counting lines and then counting entries in the legend). One solution to this problem would be to allow the placing of the assembly name at the left end of each of the colored lines to identify the assembly name.

**Comment by mnshgl0110** [comment]
Thanks for the suggestion. In principle, I agree with it but I am unsure how much work this would be. Will try to incorporate it in the next set of updates.

**Comment by mnshgl0110** [comment]
Added a new option `genname` in base.cfg that can be used to toggle genome name annotation (https://github.com/schneebergerlab/plotsr/commit/0a425240ab49c73949955f1376fb4839dd0d7320).

![tmp1](https://github.com/schneebergerlab/plotsr/assets/16225647/7a5d1799-57ae-4276-b3f1-94e421c17370)
