### ISSUE TITLE
How to set parameters to avoid the problem of incomplete start and end display？

### ISSUE THREAD

**Issue by felixlee0608** [schneebergerlab/plotsr#77]
<img width="1025" alt="plotsr-q" src="https://github.com/schneebergerlab/plotsr/assets/33302799/44a60316-0465-4d3d-9cd5-d420880a4089">

**Comment by mnshgl0110** [comment]
Currently, it is not possible to adjust this easily. You can try changing the line:
https://github.com/schneebergerlab/plotsr/blob/d045d4ef2209dee23c69b60200304c34a3fd33c4/plotsr/scripts/func.py#L1714

to:
```ax.plot(m.start, indent-offset, marker=m.mt, color=m.mc, markersize=m.ms, zorder=10)```

and then recompile plotsr. That should then plot the markers on top of other plot elements.
