### ISSUE TITLE
Readability of marker text

### ISSUE THREAD

**Issue by buchanri** [schneebergerlab/plotsr#88]
Hello, I have a question. Is it possible for the markers.bed file to specify that the markers label be place vertically for readability? Or add the markers text/color to the legend? Thank you for any feedback.
![ragout_plotsr](https://github.com/user-attachments/assets/8af636bc-41ba-424d-bee5-744bb4c3c015)

**Comment by mnshgl0110** [comment]
Currently, that is not possible. You can try using the ```tp``` in [markers.bed](https://github.com/schneebergerlab/plotsr/blob/master/example/markers.bed) tag to move the tag up/down,
