### ISSUE TITLE
Errors when using plotsr with more than 10 genomes

### ISSUE THREAD

**Issue by Chenglin20170390** [schneebergerlab/plotsr#9]
HI Manish,
 
   Many thanks for your kind reply.  I can use plotsr to draw a figure no more than 10 genomes. If more than 10 genomes, it will occur errors like below.
```
Traceback (most recent call last):
  File "/home/chenglin/softwares/plotsr/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/home/chenglin/softwares/miniconda3/envs/py39/lib/python3.9/site-packages/plotsr/main.py", line 54, in main
    plotsr(args)
  File "/home/chenglin/softwares/miniconda3/envs/py39/lib/python3.9/site-packages/plotsr/plotsr.py", line 161, in plotsr
    chrlengths, genomes = validalign2fasta(alignments, args.genomes.name)
  File "/home/chenglin/softwares/miniconda3/envs/py39/lib/python3.9/site-packages/plotsr/func.py", line 775, in validalign2fasta
    CHRCOLS = [j for i in range(int(count/2)) for j in [CHRCOLS[i]] + [CHRCOLS[int(i +count/2)]]] + [m]
UnboundLocalError: local variable 'm' referenced before assignment
```

**Comment by mnshgl0110** [comment]
Hi Lin,

It should be fixed with https://github.com/schneebergerlab/plotsr/commit/6c4dbc9c250bd63f7f3eb4ee321209e2ccb0afac

Please update using:
```
git clone https://github.com/schneebergerlab/plotsr.git
cd plotsr
python setup.py install
```
Let me know if there are more issue.

Best
Manish

**Comment by Chenglin20170390** [comment]
Thanks ! it's solved perfectly.

**Comment by Chenglin20170390** [comment]
Hi Manish,

  Another question about 10+ genomes, I just  checked the  figure. Unable to clearly distinguish structural variants in plotsr output although it works for 10+ genomes.
<img width="973" alt="image" src="https://user-images.githubusercontent.com/33062118/155052127-55a2b6f9-bd7f-4b5a-84f9-ceca32ded01e.png">

**Comment by mnshgl0110** [comment]
You can decrease the line width of the genome using the 'lw' tag in the genomes.txt file. Also, I think increasing the height of the plot would help in better visualising the differences.

**Comment by Chenglin20170390** [comment]
Thanks
